$background = 0d0f09
$onBackground = e5e7d6
$surface = 0d0f09
$surfaceDim = 0d0f09
$surfaceBright = 2b2d22
$surfaceContainerLowest = 000000
$surfaceContainerLow = 12140d
$surfaceContainer = 181a12
$surfaceContainerHigh = 1e2117
$surfaceContainerHighest = 24271c
$onSurface = e5e7d6
$surfaceVariant = 24271c
$onSurfaceVariant = aaac9d
$outline = 747769
$outlineVariant = 46493d
$inverseSurface = fbfaef
$inverseOnSurface = 55564e
$shadow = 000000
$scrim = 000000
$surfaceTint = becd96
$primary = becd96
$primaryDim = b1bf8a
$onPrimary = 39441b
$primaryContainer = 4b572c
$onPrimaryContainer = dbeab1
$inversePrimary = 586437
$primaryFixed = dae9b1
$primaryFixedDim = ccdba3
$onPrimaryFixed = 38441b
$onPrimaryFixedVariant = 546034
$secondary = c3caaa
$secondaryDim = b5bc9d
$onSecondary = 3c432b
$secondaryContainer = 383e26
$onSecondaryContainer = bcc3a3
$secondaryFixed = dfe6c4
$secondaryFixedDim = d1d8b7
$onSecondaryFixed = 3b422a
$onSecondaryFixedVariant = 585e44
$tertiary = fff3d7
$tertiaryDim = fae19c
$onTertiary = 6b5a23
$tertiaryContainer = fde49e
$onTertiaryContainer = 63521b
$tertiaryFixed = fde49e
$tertiaryFixedDim = eed591
$onTertiaryFixed = 4f3f09
$onTertiaryFixedVariant = 6d5c24
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 6f7c4d
$secondaryPaletteKeyColor = 737a5e
$tertiaryPaletteKeyColor = 88753b
$neutralPaletteKeyColor = 777870
$neutralVariantPaletteKeyColor = 76786a
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 6f7c4d
$secondary_paletteKeyColor = 737a5e
$tertiary_paletteKeyColor = 88753b
$neutral_paletteKeyColor = 777870
$neutral_variant_paletteKeyColor = 76786a
$term0 = 353433
$term1 = 9f9300
$term2 = bed763
$term3 = e4ee73
$term4 = 92b482
$term5 = c6a844
$term6 = b6d388
$term7 = dadac2
$term8 = a5a492
$term9 = b8ab00
$term10 = cbea61
$term11 = effe75
$term12 = b5c7a3
$term13 = d0bf6a
$term14 = c8e690
$term15 = ffffff
$rosewater = f6f1e1
$flamingo = e9e2c2
$pink = ffd79d
$mauve = ffad7f
$red = c9b440
$maroon = cdbf74
$peach = d3d186
$yellow = f1f5c4
$green = caeb95
$teal = c5ebaa
$sky = b8e8a8
$sapphire = 9bd694
$blue = 75cf9d
$lavender = 89dcc6
$klink = 4e9657
$klinkSelection = 4f9657
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = 978900
$knegativeSelection = 988900
$kneutral = b2b000
$kneutralSelection = b3af00
$kpositive = 84b83e
$kpositiveSelection = 85b83d
$text = e5e7d6
$subtext1 = aaac9d
$subtext0 = 747769
$overlay2 = 65685b
$overlay1 = 56594d
$overlay0 = 484a40
$surface2 = 3a3c33
$surface1 = 2c2e26
$surface0 = 1c1e17
$base = 0d0f09
$mantle = 0d0f09
$crust = 0c0e09
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
